# Generated by Django 5.2.1 on 2025-05-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=500)),
                ('uploadedFile', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('isPreprocessed', models.BooleanField(default=False)),
                ('vocabSize', models.IntegerField(blank=True, null=True)),
                ('numBatches', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runName', models.CharField(max_length=255)),
                ('hiddenDim1Size', models.IntegerField()),
                ('hiddenDim2Size', models.IntegerField()),
                ('latentDimSize', models.IntegerField()),
                ('numEpochs', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('modelPath', models.CharField(blank=True, max_length=500, null=True)),
                ('finalLoss', models.FloatField(blank=True, null=True)),
                ('coherenceScore', models.FloatField(blank=True, null=True)),
                ('diversityScore', models.FloatField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicModeller.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testLoss', models.FloatField()),
                ('reconstructionLoss', models.FloatField()),
                ('klLoss', models.FloatField()),
                ('coherenceScore', models.FloatField(blank=True, null=True)),
                ('diversityScore', models.FloatField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('trainingRun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicModeller.trainingrun')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validationLoss', models.FloatField()),
                ('reconstructionLoss', models.FloatField()),
                ('klLoss', models.FloatField()),
                ('coherenceScore', models.FloatField(blank=True, null=True)),
                ('diversityScore', models.FloatField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('trainingRun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicModeller.trainingrun')),
            ],
        ),
    ]
