# Generated by Django 5.2.1 on 2025-05-18 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicModeller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='isMarkedTrained',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('resultsPath', models.CharField(blank=True, max_length=500, null=True)),
                ('totalLoss', models.FloatField(blank=True, null=True)),
                ('coherenceScore', models.FloatField(blank=True, null=True)),
                ('diversityScore', models.FloatField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicModeller.dataset')),
                ('trainingRun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicModeller.trainingrun')),
            ],
        ),
    ]
